version: "3.9"
services:
  recboauth:
    build: .
    ports:
      - 8120:8120
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  usercredentials:
    image: typesense/typesense:0.22.2
    environment:
        TYPESENSE_DATA_DIR: /data
        TYPESENSE_API_KEY: banana
    expose:
      - 8108
    volumes: 
     - typesense-credential-data:/data

volumes:
  typesense-credential-data:
    driver: local